name: Docker Image CI

on:
    push:
        branches: [ master, dev ]

    pull_request:
        branches: [ master, dev ]

jobs:

    build:
    
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
    
        steps:
        - uses: actions/checkout@v2
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag pwabuilder.azurecr.io/pwa-screenshots:latest
      
        - name: Login
          run: docker login pwabuilder.azurecr.io -u pwabuilder --password ${{secrets.azure}}
          
        - name: Push
          run: docker push pwabuilder.azurecr.io/pwa-screenshots:latest
          
    build-prod-pr:
    
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master' && github.event.name == 'pull_request'
    
        steps:
        - uses: actions/checkout@v2
        - name: Build the Docker image
          run: docker build . --file Dockerfile 
          
    build-dev:
    
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/dev'
    
        steps:
        - uses: actions/checkout@v2
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag pwabuilder.azurecr.io/pwa-screenshots-dev:latest
      
        - name: Login
          run: docker login pwabuilder.azurecr.io -u pwabuilder --password ${{secrets.azure}}
          
        - name: Push
          run: docker push pwabuilder.azurecr.io/pwa-screenshots-dev:latest
      
    build-dev-pr:
    
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/dev' && github.event.name == 'pull_request'
    
        steps:
        - uses: actions/checkout@v2
        - name: Build the Docker image
          run: docker build . --file Dockerfile 
